import * as React from "react";
import {
  Button,
  DataList,
  DataListCell,
  DataListContent,
  DataListItem,
  DataListItemCells,
  DataListItemRow,
  DataListToggle,
  DescriptionList,
  DescriptionListDescription,
  DescriptionListGroup,
  DescriptionListTerm,
  Grid,
  GridItem,
  PageSection,
  Title,
} from "@patternfly/react-core";
import {
  CheckIcon,
  CodeBranchIcon,
  CubeIcon,
  PlusCircleIcon,
} from "@patternfly/react-icons";

const ImageCardHolder: React.FunctionComponent = () => {
  const [expanded, setExpanded] = React.useState(["falcon-sensor"]);

  const toggle = (id) => {
    const index = expanded.indexOf(id);
    const newExpanded =
      index >= 0
        ? [
            ...expanded.slice(0, index),
            ...expanded.slice(index + 1, expanded.length),
          ]
        : [...expanded, id];
    setExpanded(newExpanded);
  };

  return (
    <PageSection hasBodyWrapper={false}>
      <Title headingLevel="h1" size="lg">
        Container Images
      </Title>
      <DataList aria-label="Mixed expandable data list example">
        <DataListItem isExpanded={expanded.includes("falcon-sensor")}>
          <DataListItemRow>
            <DataListToggle
              onClick={() => toggle("falcon-sensor")}
              isExpanded={expanded.includes("falcon-sensor")}
              id="falcon-sensor"
            />
            <DataListItemCells
              dataListCells={[
                <DataListCell isIcon key="icon">
                  <CubeIcon />
                </DataListCell>,
                <DataListCell>
                  <Title headingLevel="h3">falcon-sensor</Title>
                  <p>
                    Falcon Linux sensor as a container image, to be run as a
                    Kubernetes DaemonSet.
                  </p>
                </DataListCell>,
                <DataListCell>
                  <DescriptionList
                    columnModifier={{
                      default: "2Col",
                    }}
                  >
                    <DescriptionListGroup>
                      <DescriptionListTerm>Latest tag</DescriptionListTerm>
                      <DescriptionListDescription>
                        <code>7.20.0-17306-1.falcon-linux.Release.US-2</code>
                      </DescriptionListDescription>
                    </DescriptionListGroup>
                    <DescriptionListGroup>
                      <DescriptionListTerm>Multi-arch</DescriptionListTerm>
                      <DescriptionListDescription>
                        <CheckIcon /> Yes
                      </DescriptionListDescription>
                    </DescriptionListGroup>
                  </DescriptionList>
                </DataListCell>,
              ]}
            />
          </DataListItemRow>
          <DataListContent
            aria-label="First mixed expandable content details"
            isHidden={!expanded.includes("falcon-sensor")}
          >
            <Grid>
              <GridItem span={4}>
                <DescriptionList>
                  <DescriptionListGroup>
                    <DescriptionListTerm>Latest image name</DescriptionListTerm>
                    <DescriptionListDescription>
                      <code>
                        registry.crowdstrike.com/falcon-sensor/us-2/release/falcon-sensor:7.20.0-17306-1.falcon-linux.Release.US-2
                      </code>
                    </DescriptionListDescription>
                  </DescriptionListGroup>
                  <DescriptionListGroup>
                    <DescriptionListTerm>Older tags</DescriptionListTerm>
                    <DescriptionListDescription>
                      <ul>
                        <li>
                          <code>
                            6.35.0-13206.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.35.0-13207.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.37.0-13402.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.38.0-13501.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.39.0-13601.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.40.0-13706.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.40.0-13707.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.41.0-13803.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.41.0-13804.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.43.0-14006.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.44.0-14108.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.45.0-14203.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.46.0-14306.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.47.0-14408.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.48.0-14504.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.48.0-14511.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.49.0-14604.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.49.0-14611.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.50.0-14712.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.50.0-14713.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.51.0-14809.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.51.0-14810.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.51.0-14812.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.51.0-14812.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.53.0-15003.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.53.0-15003.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.54.0-15110.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.54.0-15110.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.56.0-15309.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.56.0-15309.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.57.0-15402.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.57.0-15402.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.58.0-15508.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            6.58.0-15508.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.01.0-15604.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.01.0-15604.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.02.0-15705.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.02.0-15705.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.03.0-15805.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.03.0-15805.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.04.0-15907.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.04.0-15907.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.05.0-16004-1.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.05.0-16004-1.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.06.0-16108-1.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.06.0-16108-1.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.07.0-16206-1.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.07.0-16206-1.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.10.0-16303-1.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.10.0-16303-1.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.11.0-16404-1.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.11.0-16404-1.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.11.0-16405-1.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.11.0-16405-1.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.11.0-16407-1.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.11.0-16407-1.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.13.0-16604-1.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.13.0-16604-1.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.14.0-16703-1.falcon-linux.aarch64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>
                            7.14.0-16703-1.falcon-linux.x86_64.Release.US-2
                          </code>
                        </li>
                        <li>
                          <code>7.15.0-16803-1.falcon-linux.Release.US-2</code>
                        </li>
                        <li>
                          <code>7.15.0-16805-1.falcon-linux.Release.US-2</code>
                        </li>
                        <li>
                          <code>7.16.0-16903-1.falcon-linux.Release.US-2</code>
                        </li>
                        <li>
                          <code>7.16.0-16907-1.falcon-linux.Release.US-2</code>
                        </li>
                        <li>
                          <code>7.17.0-17005-1.falcon-linux.Release.US-2</code>
                        </li>
                        <li>
                          <code>7.17.0-17011-1.falcon-linux.Release.US-2</code>
                        </li>
                        <li>
                          <code>7.18.0-17106-1.falcon-linux.Release.US-2</code>
                        </li>
                        <li>
                          <code>7.18.0-17129-1.falcon-linux.Release.US-2</code>
                        </li>
                        <li>
                          <code>7.19.0-17219-1.falcon-linux.Release.US-2</code>
                        </li>
                        <li>
                          <code>7.20.0-17306-1.falcon-linux.Release.US-2</code>
                        </li>
                      </ul>
                    </DescriptionListDescription>
                  </DescriptionListGroup>
                </DescriptionList>
              </GridItem>
              <GridItem span={8}>
                <Title headingLevel="h4">Download this image</Title>
                <p>
                  Refer to the{" "}
                  <a href="https://github.com/CrowdStrike/falcon-scripts/blob/main/bash/containers/falcon-container-sensor-pull/README.md">
                    Falcon Container Pull Script
                  </a>
                </p>
              </GridItem>
            </Grid>
          </DataListContent>
        </DataListItem>
      </DataList>
    </PageSection>
  );
};

export { ImageCardHolder };
